# Description: Constants used throughout the project
# Create a dict called CLUB_DICT where the keys are the abbreviations of the clubs and the values are integers from 0 to 32

CLUB_DICT = {
    "BUF": 0,
    "LA": 1,
    "NO": 2,
    "ATL": 3,
    "CLE": 4,
    "CAR": 5,
    "SF": 6,
    "CHI": 7,
    "CIN": 8,
    "PIT": 9,
    "PHI": 10,
    "DET": 11,
    "IND": 12,
    "HOU": 13,
    "MIA": 14,
    "NE": 15,
    "NYJ": 16,
    "BAL": 17,
    "TEN": 18,
    "NYG": 19,
    "JAX": 20,
    "WAS": 21,
    "KC": 22,
    "ARI": 23,
    "LV": 24,
    "LAC": 25,
    "MIN": 26,
    "GB": 27,
    "TB": 28,
    "DAL": 29,
    "DEN": 30,
    "SEA": 31,
    "football": 32,
}